# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
      - "python"
    commit-message:
      prefix: "NO-ISSUE"
    groups:
      python-dependencies: "PYTHON"
        patterns:
          - "^requirements.*"
      python-dev-dependencies: "PYTHON-DEV"
        patterns:
          - "^dev-requirements.*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
      - "docker"
    commit-message:
      prefix: "NO-ISSUE"
    groups:
      docker-dependencies: "DOCKER"
        patterns:
          - "*"
