FROM python:3

RUN apt-get update && apt-get install -y \
    jq \
    p7zip-full

RUN pip install pip --upgrade

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

COPY dev-requirements.txt /tmp/dev-requirements.txt
RUN pip install -r /tmp/dev-requirements.txt

RUN rm /tmp/*requirements.txt

