FROM quay.io/centos/centos:stream8

RUN dnf install -y \
    jq \
    gcc \
    git \
    make \
    skopeo \
    python39 \
    python39-pip \
    python39-devel \
        && dnf clean all

RUN alternatives --set python /usr/bin/python3.9

RUN pip3 install pip --upgrade

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY dev-requirements.txt ./
RUN pip install -r dev-requirements.txt

ARG INSTALL_CCX=true

COPY ccx/ ./ccx
RUN if [ "${INSTALL_CCX}" == "true" ]; then \
        ./ccx/install.sh; \
    fi

WORKDIR /home/assisted-installer-deployment
COPY . .

# PBR version is needed to allow us to .dockerignore the heavy .git directory
RUN PBR_VERSION=9.9.9 pip install .
