FROM quay.io/centos/centos:stream8

RUN dnf update -y && dnf install -y \
    jq \
    gcc \
    git \
    make \
    skopeo \
    python39 \
    python39-pip \
    python39-devel \
    genisoimage \
        && dnf clean all

# required for generating configuration in assisted-service repo
RUN curl https://mirror.openshift.com/pub/openshift-v4/clients/butane/latest/butane --output /usr/local/bin/butane \
    && chmod +x /usr/local/bin/butane

RUN alternatives --set python /usr/bin/python3.9

RUN pip3 install pip --upgrade

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

COPY dev-requirements.txt /tmp/dev-requirements.txt
RUN pip install -r /tmp/dev-requirements.txt

WORKDIR /home/assisted-installer-deployment
COPY . .

RUN pip install .
