FROM python:3

RUN apt-get update && apt-get install -y \
    jq \
    p7zip-full

RUN pip install pip --upgrade

RUN curl -fsSL https://get.docker.com -o get-docker.sh
RUN sh get-docker.sh

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

COPY dev-requirements.txt /tmp/dev-requirements.txt
RUN pip install -r /tmp/dev-requirements.txt
#RUN pip install strato-skipper

RUN rm /tmp/*requirements.txt
