all: pycodestyle pylint build

.PHONY: pycodestyle pylint clean build
build:
	python setup.py sdist

pycodestyle:
	pycodestyle .

pylint:
	mkdir -p reports
	PYLINTHOME=reports/ pylint release

clean:
	rm -rf build dist *egg-info ./__pycache__
	find -name *.pyc -delete
